In [1]:
import os
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
plt.rcParams['font.sans-serif'] = 'SimHei'   # 显示中文

In [2]:
data = pd.read_csv('data_wuliu.csv', encoding='gbk')
data

,订单号,订单行,销售时间,交货时间,货品交货状况,货品,货品用户反馈,销售区域,数量,销售金额
0,P096311,10,2016/7/30,2016/9/30,晚交货,货品3,质量合格,华北,2.0,"1052,75元"
1,P096826,10,2016/8/30,2016/10/30,按时交货,货品3,质量合格,华北,10.0,"11,50万元"
2,NaN,20,2016/8/30,2016/10/30,按时交货,货品3,质量合格,华北,10.0,"11,50万元"
3,P097435,10,2016/7/30,2016/9/30,按时交货,货品1,返修,华南,2.0,"6858,77元"
4,P097446,60,2016/11/26,2017/1/26,晚交货,货品3,质量合格,华北,15.0,"129,58元"
...,...,...,...,...,...,...,...,...,...,...
1156,P299901,10,2016/12/15,2017/3/15,按时交货,货品6,质量合格,马来西亚,2.0,"200,41元"
1157,P302956,10,2016/12/22,2017/3/22,按时交货,货品2,拒货,华东,20.0,"79,44元"
1158,P303801,10,2016/12/15,2017/3/15,按时交货,货品2,质量合格,华东,1.0,"194,08元"
1159,P307276,10,2016/12/22,2017/3/22,按时交货,货品6,质量合格,马来西亚,1.0,"32,18元"
1160,P314165,10,2016/12/20,2017/3/20,按时交货,货品2,质量合格,华东,1.0,"1720,92元"

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1161 entries, 0 to 1160
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   订单号     1159 non-null   object
 1   订单行     1161 non-null   int64
 2   销售时间    1161 non-null   object
 3   交货时间    1161 non-null   object
 4   货品交货状况  1159 non-null   object
 5   货品      1161 non-null   object
 6   货品用户反馈  1161 non-null   object
 7   销售区域    1161 non-null   object
 8   数量      1157 non-null   float64
 9   销售金额    1161 non-null   object
dtypes: float64(1), int64(1), object(8)
memory usage: 90.8+ KB

- 订单号、货品交货情况、数量存在缺失值
- 订单行无关紧要，可删除
- 销售金额格式不对，数据类型要改成int/float

In [4]:
# 删除重复记录
data.drop_duplicates(keep='first',inplace=True)

# 删除缺失值
data.dropna(axis=0,how='any',inplace=True)

#删除订单行
# 只要运行一次，再次运行由于已删会报错
# data.drop(columns=['订单行'],inplace=True,axis=1) 
# 改成如果存在则删除
if '订单行' in data.columns:
    data.drop(columns=['订单行'], inplace=True)
print(data.info())
# 更新索引
data.reset_index(drop=True,inplace=True)

<class 'pandas.core.frame.DataFrame'>
Index: 1146 entries, 0 to 1160
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   订单号     1146 non-null   object
 1   销售时间    1146 non-null   object
 2   交货时间    1146 non-null   object
 3   货品交货状况  1146 non-null   object
 4   货品      1146 non-null   object
 5   货品用户反馈  1146 non-null   object
 6   销售区域    1146 non-null   object
 7   数量      1146 non-null   float64
 8   销售金额    1146 non-null   object
dtypes: float64(1), object(8)
memory usage: 89.5+ KB
None

In [5]:
# 对销售金额列进行数据清洗（有的是“元”，有的是“万元”）
# 自定义过滤函数（删除逗号，处理万元，转成float）
def data_deal(number):
    if '万元' in number:
        number_new = float(number.replace('万元', '').replace(',', '')) * 10000
    elif '元' in number:
        number_new = float(number.replace('元', '').replace(',', ''))
    return number_new
    
data['销售金额'] = data['销售金额'].map(data_deal)
data

,订单号,销售时间,交货时间,货品交货状况,货品,货品用户反馈,销售区域,数量,销售金额
0,P096311,2016/7/30,2016/9/30,晚交货,货品3,质量合格,华北,2.0,105275.0
1,P096826,2016/8/30,2016/10/30,按时交货,货品3,质量合格,华北,10.0,11500000.0
2,P097435,2016/7/30,2016/9/30,按时交货,货品1,返修,华南,2.0,685877.0
3,P097446,2016/11/26,2017/1/26,晚交货,货品3,质量合格,华北,15.0,12958.0
4,P097446,2016/11/26,2017/1/26,晚交货,货品3,拒货,华北,15.0,3239.0
...,...,...,...,...,...,...,...,...,...
1141,P299901,2016/12/15,2017/3/15,按时交货,货品6,质量合格,马来西亚,2.0,20041.0
1142,P302956,2016/12/22,2017/3/22,按时交货,货品2,拒货,华东,20.0,7944.0
1143,P303801,2016/12/15,2017/3/15,按时交货,货品2,质量合格,华东,1.0,19408.0
1144,P307276,2016/12/22,2017/3/22,按时交货,货品6,质量合格,马来西亚,1.0,3218.0
1145,P314165,2016/12/20,2017/3/20,按时交货,货品2,质量合格,华东,1.0,172092.0

In [7]:
data.describe()

                 数量          销售金额
count   1146.000000  1.146000e+03
mean      76.069372  1.223488e+05
std      589.416486  1.114599e+06
min        1.000000  0.000000e+00
25%        1.000000  2.941500e+03
50%        1.000000  9.476500e+03
75%        4.000000  3.576775e+04
max    11500.000000  3.270000e+07

- 销售金额最小值0
- 数据右偏明显（电商领域常见，不用管）

In [10]:
# 删除销售金额0的（数据量小，可以删除）
data = data[data['销售金额']!=0]
data.describe()

                 数量          销售金额
count   1145.000000  1.145000e+03
mean      76.134934  1.224557e+05
std      589.669861  1.115081e+06
min        1.000000  5.100000e+01
25%        1.000000  2.946000e+03
50%        1.000000  9.486000e+03
75%        4.000000  3.577300e+04
max    11500.000000  3.270000e+07

In [12]:
# 数据规整：增加辅助列——月份
data['销售时间'] = pd.to_datetime(data['销售时间'])
data['月份'] = data['销售时间'].apply(lambda x:x.month)

,订单号,销售时间,交货时间,货品交货状况,货品,货品用户反馈,销售区域,数量,销售金额,月份
0,P096311,2016-07-30,2016/9/30,晚交货,货品3,质量合格,华北,2.0,105275.0,7
1,P096826,2016-08-30,2016/10/30,按时交货,货品3,质量合格,华北,10.0,11500000.0,8
2,P097435,2016-07-30,2016/9/30,按时交货,货品1,返修,华南,2.0,685877.0,7
3,P097446,2016-11-26,2017/1/26,晚交货,货品3,质量合格,华北,15.0,12958.0,11
4,P097446,2016-11-26,2017/1/26,晚交货,货品3,拒货,华北,15.0,3239.0,11
...,...,...,...,...,...,...,...,...,...,...
1141,P299901,2016-12-15,2017/3/15,按时交货,货品6,质量合格,马来西亚,2.0,20041.0,12
1142,P302956,2016-12-22,2017/3/22,按时交货,货品2,拒货,华东,20.0,7944.0,12
1143,P303801,2016-12-15,2017/3/15,按时交货,货品2,质量合格,华东,1.0,19408.0,12
1144,P307276,2016-12-22,2017/3/22,按时交货,货品6,质量合格,马来西亚,1.0,3218.0,12
1145,P314165,2016-12-20,2017/3/20,按时交货,货品2,质量合格,华东,1.0,172092.0,12